emacs-w3m/emacs-w3m

- ChangeLog
- w3m-filter.el
Two new filters: the github filter is the one I shared a few days ago on the mailing list; the xkcd filter is because its a popular comic, and doesn't display nicely for me.
> New filters: github main repo page, xkcd

- ChangeLog
- w3m-dtree.el
To reproduce this bug, perform w3m-dtree on a folder that has many sub-folders, one of which has been chmod'ed 0.
> bugfix: w3m-dtree shouldn't abort on subdir permission restriction

- w3mhack.el
Please verify that using "unknown" is ok.
Also I do think that checking for .git instead of .git/config is enough.
> Make w3mhack-insert-git-revision not fail without git

- ChangeLog
- w3m-filter.el
A few days ago RT changed the format of their web pages, so the prior version of the filter wasn't catching all the cruft at the bottom of the pages.
> w3m-filter-rt: update for new site footers

- ChangeLog
- w3m.el
+ This required adding an optional arg to w3m-goto-url-new-session,
and combining two duplicate and badly-used args (JUST-COPY and
BACKGROUND) in w3m-copy-buffer.
+ Both functions w3m-goto-url-new-session and w3m-copy-buffer had
undocumented use of the prefix arg. These were changed to allow
interactive toggling the default for loading in background or
foreground.
+ w3m-copy-buffer was using prefix arg for renaming a tab copy
+ w3m-goto-url-new-session was using prefix-arg for RELOAD.
+ Combining args for w3m-copy-buffer meant adjusting a few calls to
that function.
+ w3m-copy-buffer was changed to perform a buffer-clone instead of an
entire w3m processing operation. This greatly speeds up response
time.
+ There remains a seeming inconsistency in terminology in that it
seems NO-POPUP and …
> BUGFIX: allow new tabs to be loaded in background

- ChangeLog
- w3m-ems.el
- w3m.el
+ One could change the order of tabs directly, using functions
w3m-tab-move-right and w3m-tab-move-left, but not from within a
w3m-select buffer, which is a nicer environment for that kind of
operation. This commit adds functions w3m-select-buffer-move-next
and w3m-select-buffer-move-previous, which are basically wrappers
for the pre-existing ones.
+ The pre-existing functions were each bound to several keys, all of
which are un-friendly to consoles (C-., C-,, C->, C-<.), so
console-friendly alternatives were added.
+ The docstring for the w3m-select buffer mode was edited.
> Change order of tabs from within buffer listing, Update docstrings.

- ChangeLog
- w3m-search.el
* w3m-search.el (w3m-search-engine-alist): Add &gbv=1 to
www.google.com/search to prevent META refresh ([emacs-w3m:13355]).
> Prevent META refresh when Google searching

- ChangeLog
- w3m-util.el
encode-coding-string may modify unibyte string.
```lisp
(let ((string (string-to-unibyte "\300\261")))
(encode-coding-string string 'utf-8-emacs))
-> "\261"
```
> Fix: w3m-insert-string modifies string

- ChangeLog
- w3m.el
Now, pressing RETURN on a torrent or magnet link starts downloading the torrent, just like in all other browsers! As is the case for other browsers, an external program is used for the actual work. In this case, I chose the `transmission` project to do the heavy-lifting because it had a convenient set of command-line utilities including a daemon, and an NCURSES-based interface that was able to be launched within an emacs `ansi-term` buffer (see man(1) transmission-remote-cli for all its keybinding and configuration options).
> New feature: support torrent/magnet links (transmission front-end)

- ChangeLog
- w3m.el
Change `transmission-remote-cli' from required to recommended, and update documentation accordingly.
This is a follow-up to PR #37. Before merging this PR, there may be a need to make another commit here to change use of `w3m--message` to `w3m-message` (ref PR #14).
> w3m--goto-torrent-url: don't require transmission-remote-cli

- ChangeLog
- w3m-bookmark.el
+ Bugfix: Order of args to function	string-match.
+ Bugfix: Operate in all display modes.
+ Only ask for bookmark section once (ie. presume all bookmarks will
be placed in the same section).
+ Provide sane default section, timestamp-based.
+ Don't add bookmarks buffers to bookmark list (ie. recursive
bookmarks).
+ Auto-refresh existing bookmark buffers.
+ Improve error handling. Instead of aborting, log the faulty event to
the Messages buffer and continue.
+ Add tab character to whitespace regexp.
+ Use function set-buffer instead of switch-to-buffer.
> w3m-bookmark-add-all-urls: feature improvements, bug-fixes

- ChangeLog
- w3m-session.el
This PR fixes three bugs with session management:
+ When opening a session or one of its elements:
+ don't quit the session buffer; allow the user to continue working
on it.
+ don't forget the window in which the w3m session buffer was being
displayed.
+ don't create duplicate buffers
> Preserve session buffer/window and don't create duplicate buffers

- ChangeLog
- w3m-session.el
+ Copies either a single session entry (ie. a URL) or an entire
session list of entries into a second existing session.
+ This is desirable for managing URLS that have accumulated over time
into different sessions and need to be re-organized.
+ Currently, identical duplicates are avoided, meaning that if two
entries are for the same URL, but have different other details, such
as cursor position or HTML form data, then both are saved. However,
that may be turn out to be too conservative, and it may prove
desirable to prune based just on duplicate URLs.
+ Bound to 'm' and 'M' on the local keymap
> w3m-session-select-merge: New feature: combine session data

- w3m.el
Hi,
I'd like to put the call to `w3m-select-buffer-show-this-line` in `w3m-select-buffer-delete-buffer` after the call to `goto-char` so that the buffer on the current menu line is shown at the end. Otherwise the first buffer in the menu is shown, while the point has already moved.
> Change the order of show-this-line in w3m-select-buffer-delete-buffer

- ChangeLog
- w3mhack.el
When FLIM is installed and SEMI is not, `make` causes the
following error.
```
Compiling mime-w3m.el...
In toplevel form:
mime-w3m.el:37:1:Error: Cannot open load file: No such file or directory, mime-view
```
With the recent commit b5ec8774 on 2019-06-17, mime-w3m.el requires
SEMI's mime-view.el instead of FLIM's one, so I've added a check for
mime-view.el existence.
> Don't byte-compile mime-w3m.el when SEMI is not installed

- w3m-session.el
I use long-lived sessions with many buffers and lots of history within
each.  Sometimes, when loading such a session, I get an error
(wrong-type-argument consp nil) or something like that.  I will not
report that exact problem here for now, because currently I don't have
such a session, and if I had it then it would be complex.
I took a look at the code responsible for saving/restoring sessions
and found two problems, which I believe take part in my original
problem.  What I plan is to live with these fixes for a while and see
if anything goes wrong again.  If I reproduce the original problem,
I'll try to report it with minimal test case.
So this PR contains fixes for the code which I'm sure is wrong in
master (assuming I'm not wrong when reading the code).
I had a test w3m session: …
> Fix saving and restoring of a session

- w3m-perldoc.el
- w3m-util.el
Currently the `w3m-perldoc` command has the base URL `about://perldoc/` hardcoded into the function call. I added a `defcustom`, changed the default to `https://perldoc.perl.org/`, and added a function that attempts to cleanup user input in a way more likely to match a page.
Personally I am going to clone their github and have a local copy to lookup with, which is why I needed the URL to be customizable. Here is what I have in my config:
```emacs-lisp
(setq perl-version "5.30.0")
(setq w3m-perldoc-base-url (concat "file:///home/user/perl5/perldoc/"
perl-version))
```
Try running:
`(w3m-perldoc "Pod Checker")`
which will send you off to https://perldoc.perl.org/Pod/Checker.html#perl_version
or
`(w3m-perldoc "Getopt::Long")`
TODO:
- Improve the cleanup to deal with other things (like …
> Improve perldoc with customizable variable, and saner default.

- ChangeLog
- doc/emacs-w3m-ja.texi
* doc/emacs-w3m-ja.texi (Installing Emacs-w3m): Add dropped @samp
command for --without-compress-install option.
> Fix document typo

- ChangeLog
- w3m-session.el
- w3m.el
Variable buffer-quit-function is used by function
keyboard-escape-quit to decide how to exit a buffer when pressing a
keybinding such as ESC-ESC-ESC. Without setting the variable for the
w3m-session and w3m-select modes, the action taken is to hide all
the *other* windows on the current frame. This commit has it perform
the modes' quit function.
> Set variable buffer-quit-function for -session and -select modes

- ChangeLog
- w3m-hist.el
- w3m.el
This is a one-line addition to the beginning of function w3m-history-push. It prevents the about:history page from accumulating entries of itself. What otherwise happens is that each time someone presses 'h' another copy of the history is added to the history list for the buffer! Press 'h' and 'B' many times and you end up with many copies of the history in your buffer's history, when really it should appear ZERO times.
> BUGFIX: don't put about://history/ pages in history.

- ChangeLog
- w3m-proc.el
- w3m.el
+ Several instances were found of string operations being performed on
w3m-current-url without checking if the variable was a string.
+ When an external program calls emacs/emacs-w3m to open a URI that is
an image, and emacs-w3m is configured to view that filetype
externally, it still creates a new emac-w3m buffer.
+ This patch deletes the created buffer; however, wouldn't it be
better never to create it in the first place?
+ That might not be possible because the way asynchronous processes
need to be associated with a buffer, but even so the current
situation needlessly makesthe new buffer a copy of the most recent
emacs-w3m buffer.
> Fixes for w3m-current-url = NIL, loading images from ext program

- ChangeLog
- w3m-util.el
- w3m.el
+ Reference commits: c91e761f3, cc4ae1cbb
+ defcustom w3m-queries-log-file had been defined as boolean; define
it as type 'file, and improve its default location.
+ New utility function w3m--url-get-queries. I've started using it in
my w3m-download.el, but it can be useful for the query-tracker feature
and any other feature that looks at the query section of a url.
+ w3m--url-strip-queries: What an awful and misleading name I gave
that function back when. Much better name is
w3m--url-strip-unwanted-queries
> tweaks to handling url query parts

- w3m.el
By the time split-window is called, the locally let selected-window variable is no longer a valid window. Thus, we *actually* need to call the selected-window function here.
> Address error in toggling vertical/horizontal popup window splits.

- ChangeLog
- w3m.el
+ It is desirable for normal web pages to have a limited text width
because beyond a certain width, it is difficult to return to the
proper next line. However, the content of some pages does make sense
to always take advantage of the full width of a window. This commit
enables that distinction to be made, by url regex, and uses that
feature for the 'flat' history display pages, as created by M-x
w3m-db-history.
+ The layout of w3m-db-history pages is reversed to put the short and
constant width field (date/time) on the left.
+ Function w3m-about-db-history has some unusual code that directly
calls function w3m-display-width instead of via w3m-create-page, so
it was necessary there to manually set variable w3m-fill-column to
-1. I tried several other techniques, but for any other to work …
> force-wide-display

- w3m.el
This continues PR#98 with work that is discussed in the github comments there: 
+ After rendering a db-history page, advance POINT to a position that is useful for user,the first db-history entry.
+ Add a docstring to function `w3m--goto-url--handler-function`
> Bb force wide

- w3m.el
+ There's nothing "bad" about make-variable-buffer-local, but now that
emacs has had defvar-local for such a long time, there's benefit in
preferring it for readability and maintainability
> Replace obsolete forms

- ChangeLog
- w3m-filter.el
+ The former filter was written over two years ago, only covers
repository home pages, and only in a minimal fashion.
+ The proposed replacement covers many/most pages of the github site,
makes content much easier to read and navigate, and prunes out cruft
and artifacts associated with javascript page functions that won't
work in emacs-w3m.
+ Some of the things now pleasant and easy to do:
+ search for repositories using github's own powerful search engine
+ browse a user's contribution history
+ browse a user's repositories
+ search, sort, and view issues and PR's
+ view stars and followers
+ probably more...
> w3m-filter: new and improved filter for github

- ChangeLog
- w3m.el
1 Variable w3m-user-agent-default-alist
+ It had been defined as a macro, but the macro was specifying a
symbol when the value of that symbol was needed.
+ To reproduce the bug:
+ Evaluate variable w3m-user-agent
+ M-x w3m-user-agent-change to something other than the default
+ Evaluate variable w3m-user-agent
+ M-x w3m-user-agent-change to the default
+ Evaluate variable w3m-user-agent
2 The former values in variable w3m-user-agent-alist have aged, and
are no longer popular or current.
+ I took the list from a firefox browser extension, but here's a
resource that may be easier scrape in the future:
https://raw.githubusercontent.com/Kikobeats/top-user-agents/master/index.json
3 Variable w3m-user-agent-site-specific-alist had previously required
explicitly entering a user-agent string, but …
> user-agents: bugfix, update, improve friendliness
